# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [15]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [16]:
city_data = pd.read_csv("../WeatherPy/clean_city_data")
city_data

,City,Country,Latitude,Longitude,Cloudiness,Humidity,Max Temperature,Wind Speed
0,Sitka,US,57.052497,-135.337612,100,71,12.90,4.12
1,Sydney,AU,-33.768528,150.956856,73,69,17.86,1.79
2,Punta arenas,CL,-53.162569,-70.907822,75,86,-1.84,3.09
3,Kapaa,US,22.074733,-159.319160,100,85,27.99,6.17
4,Ordzhonikidze,UA,44.964080,35.358029,98,59,22.24,3.63
...,...,...,...,...,...,...,...,...
528,Kijang,ID,0.424571,101.630480,74,57,30.99,0.72
529,Wellington,NZ,-41.288795,174.777211,75,78,10.94,11.32
530,Chernogorsk,RU,53.828236,91.313210,0,53,23.24,2.00
531,Reyes,BO,-14.295219,-67.335855,93,70,17.76,0.67
532,Miloslavskoye,RU,53.579839,39.445062,100,69,18.47,5.11

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [17]:
gmaps.configure(api_key=g_key)

locations = city_data[['Latitude', 'Longitude']]
weights = city_data['Humidity']
figure_layout= {
    'width': '1200px',
        'height': '600px',
        'padding': '3px',
        'border': '1px solid black'
}
fig = gmaps.figure(zoom_level=2,center=[10,50],layout=figure_layout)
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights, max_intensity=20))

fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', padding='3px', width='1200px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [18]:
# Ideal weather conditions
# A Max Temp above 25 and below 40
# Zero cloudiness
# Humidity between 40 to 60%

hotel_df = pd.DataFrame(city_data.loc[(city_data["Max Temperature"] >= 25) & (city_data["Max Temperature"] <= 40) 
                                              & (city_data["Cloudiness"] == 0) & (city_data["Humidity"] >= 40) 
                                               & (city_data["Humidity"] <= 60)])
hotel_df

,City,Country,Latitude,Longitude,Cloudiness,Humidity,Max Temperature,Wind Speed
212,Jalu,LY,29.033115,21.548221,0,42,26.06,1.10
318,Asmar,AF,35.033328,71.358087,0,50,27.33,3.98
338,Qianan,CN,39.997842,118.694990,0,43,32.23,4.49
354,Dongying,CN,37.433474,118.668935,0,41,33.26,4.96
400,Saint-pierre,FR,48.383272,7.471873,0,54,25.70,2.30

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [19]:
hotel_df["Hotel Name"]=""

for index,row in hotel_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
    
    latitude = row["Latitude"]
    longitude = row["Longitude"]
    locations = f"{latitude},{longitude}"
    
    params = {"key": g_key,
              "location":locations,
             "radius":5000,
             "keyword":"hotel"}
    
    response = requests.get(base_url,params)
    hotel_name = response.json()
    
    if hotel_name["status"] == "OK":
        hotel_df.loc[index, "Hotel Name"] = hotel_name["results"][0]["name"]
    else:
        hotel_df.loc[index, "Hotel Name"] = "None Found"
        
hotel_df

,City,Country,Latitude,Longitude,Cloudiness,Humidity,Max Temperature,Wind Speed,Hotel Name
212,Jalu,LY,29.033115,21.548221,0,42,26.06,1.10,Ø¥Ø³ØªØ±Ø§Ø­Ø© ØµÙ„Ø§Ø­ Ø§Ù„ØµØ§Ø¯Ù‚
318,Asmar,AF,35.033328,71.358087,0,50,27.33,3.98,None Found
338,Qianan,CN,39.997842,118.694990,0,43,32.23,4.49,Qian'an Jinjiang Hotel
354,Dongying,CN,37.433474,118.668935,0,41,33.26,4.96,Luxury Blue Horizon Hotel Dongying
400,Saint-pierre,FR,48.383272,7.471873,0,54,25.70,2.30,HÃ´tel Kieffer

In [20]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""

# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [21]:
# Add marker layer ontop of heat map

marker_layer = gmaps.marker_layer(
        locations)

marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info,
    display_info_box=True)
fig.add_layer(marker_layer)

# Display figure
fig

Figure(layout=FigureLayout(border='1px solid black', height='600px', padding='3px', width='1200px'))